package io.skyfii.mandrill.model

// See https://mandrillapp.com/api/docs/messages.JSON.html
case class Message(html: String,
                   text: Option[String],
                   subject: String,
                   from_email: String,
                   from_name: Option[String],
                   to: Vector[Recipient],
                   headers: Map[String, String] = Map(),
                   important: Boolean = false,
                   track_opens: Boolean = true,
                   track_clicks: Boolean = true,
                   auto_text: Boolean = true,
                   auto_html: Boolean = true,
                   inline_css: Boolean = false,
                   url_strip_qs: Boolean = false,
                   preserve_recipients: Boolean = true,
                   view_content_link: Boolean = true,
                   bcc_address: Option[String] = None,
                   tracking_domain: Option[String] = None,
                   signing_domain: String = "",
                   return_path_domain: String = "",
                   merge: Boolean = false,
                   merge_language: Option[String] = None,
                   global_merge_vars: Vector[MergeVar] = Vector(),
                   merge_vars: Vector[RecipientMergeVars] = Vector(),
                   tags: Vector[String] = Vector(),
                   subaccount: Option[String] = None,
                   google_analytics_domains: Vector[String] = Vector(),
                   google_analytics_campaign: Option[String] = None,
                   metadata: Map[String, String] = Map(),
                   recipient_metadata: Vector[RecipientMetadata] = Vector(),
                   attachments: Vector[Attachment] = Vector(),
                   images: Vector[Image] = Vector())
